# 服务端口
server:
  port: 9000
  servlet:
    context-path: /admin    # 服务根路径
spring:
  application:
    name: microservice-service-admin # 服务注册名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 2                                         # 启动连接池时，初始建立的连接数量
      min-idle: 1                                             # 接池最小的空闲连接数量
      max-active: 5                                           # 连接池中最大的活跃连接数
      max-wait: 60000                                         # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000                  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒


# 注册中心配置参数
eureka:
  client:
    service-url:
      defaultZone: http://39.105.179.56:8761/eureka/
  instance:
    prefer-ip-address: true           # 优先使用IP注册
    metadata-map:
      context-path: ${server.servlet.context-path}
      port: ${server.port}

# mybatisplus配置参数
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml                  # classpath* 加上星号后可扫描所有子包指定目录下的文件
  type-aliases-package: com.dasorb.framworkadmin.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl