# spring设置
spring:
  application:
    name: microservice-cloud-eureka         # 服务注册名称
server:
  port: 8761 # 服务端口

# cloud设置
eureka:
  client:
    register-with-eureka: false # 是否将自己注册到EurekaServer，默认为true
    fetch-registry: false       # 是否从EurekaServer获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/ # 设置与EurekaServer交互的地址，多个地址可使用，分割
  instance:
    prefer-ip-address: true # 使用ip地址注册到服务中心
  ###### 测试用 ##########
  server:
    evictionIntervalTimerInMs: 20000 #每间隔30秒剔除一次下线的服务
    enableSelfPreservation: false #关闭Eureka的自我保护
  ##### 测试用 ##########

